# THIS IS AN AUTOGENERATED FILE
# Made by prepareSamples.py
# do NOT modify (except to skip individual samples)


import FWCore.ParameterSet.Config as cms
from TTH.MEAnalysis.samples_base import *

version = "Aug2"
samples_dict = {
 
        "QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8": cms.PSet(
            name     = cms.string("QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8"),
            nickname = cms.string("QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8"),
            isMC     = cms.bool(True),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files("$CMSSW_BASE/src/TTH/MEAnalysis/gc/datasets/had_V24/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt")),
        ),
     
        "ttHTobb_M125_13TeV_powheg_pythia8": cms.PSet(
            name     = cms.string("ttHTobb_M125_13TeV_powheg_pythia8"),
            nickname = cms.string("ttHTobb_M125_13TeV_powheg_pythia8"),
            isMC     = cms.bool(True),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files("$CMSSW_BASE/src/TTH/MEAnalysis/gc/datasets/had_V24/ttHTobb_M125_13TeV_powheg_pythia8.txt")),
        ),
     
        "BTagCSV": cms.PSet(
            name     = cms.string("BTagCSV"),
            nickname = cms.string("BTagCSV"),
            isMC     = cms.bool(True),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files("$CMSSW_BASE/src/TTH/MEAnalysis/gc/datasets/had_V24/BTagCSV.txt")),
        ),
     
        "QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8": cms.PSet(
            name     = cms.string("QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8"),
            nickname = cms.string("QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8"),
            isMC     = cms.bool(True),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files("$CMSSW_BASE/src/TTH/MEAnalysis/gc/datasets/had_V24/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt")),
        ),
     
        "TT_TuneCUETP8M1_13TeV-powheg-pythia8": cms.PSet(
            name     = cms.string("TT_TuneCUETP8M1_13TeV-powheg-pythia8"),
            nickname = cms.string("TT_TuneCUETP8M1_13TeV-powheg-pythia8"),
            isMC     = cms.bool(True),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files("$CMSSW_BASE/src/TTH/MEAnalysis/gc/datasets/had_V24/TT_TuneCUETP8M1_13TeV-powheg-pythia8.txt")),
        ),
     
        "ttHToNonbb_M125_13TeV_powheg_pythia8": cms.PSet(
            name     = cms.string("ttHToNonbb_M125_13TeV_powheg_pythia8"),
            nickname = cms.string("ttHToNonbb_M125_13TeV_powheg_pythia8"),
            isMC     = cms.bool(True),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files("$CMSSW_BASE/src/TTH/MEAnalysis/gc/datasets/had_V24/ttHToNonbb_M125_13TeV_powheg_pythia8.txt")),
        ),
    }
